- name: nginx
  host: web
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.package:
     name: nginx
     state: latest
  - name: start the nginx 
    ansible.builtin.service:
      name: nginx
      state: enable
 
