- name : Install and run the nginx server
  hosts: all
  become: yes
  tasks:
  - name: Install the nginx
    ansible.builtin.dnf:
     name: nginx
     state: latest 
  - name: Start the nginx
    ansible.builtin.service:
     name: nginx
     state: started
     enabled: yes
  - name : installting the github 
    ansible.builtin.dnf:
     name: github
     state: present

